import { Platform, StyleSheet } from 'react-native';
import { APP_FONT, COLORS } from '../constants';

export const chatComposerStyles = StyleSheet.create({
  inputWrap: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.bg,
    paddingBottom: Platform.OS === 'ios' ? 4 : 8,
  },
  previewWrap: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 4,
  },
  previewThumb: {
    width: 68,
    height: 68,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  previewRemove: {
    position: 'absolute',
    top: 4,
    left: 72,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewRemoveText: {
    ...APP_FONT,
    color: '#fff',
    fontSize: 10,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  attachBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachBtnActive: {
    backgroundColor: COLORS.accentDim,
    borderColor: COLORS.accent + '66',
  },
  attachIcon: {
    ...APP_FONT,
    fontSize: 20,
    color: COLORS.muted,
  },
  input: {
    ...APP_FONT,
    flex: 1,
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    fontSize: 15,
    color: COLORS.text,
    maxHeight: 120,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnOff: {
    backgroundColor: COLORS.accentDim,
    opacity: 0.5,
  },
  sendIcon: {
    ...APP_FONT,
    color: '#fff',
    fontSize: 14,
    marginTop: -1,
  },
  stopBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopIcon: {
    ...APP_FONT,
    color: '#fff',
    fontSize: 12,
  },
});
